# Generated by Django 4.2.7 on 2023-11-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('eventId', models.IntegerField()),
                ('event', models.CharField(max_length=255)),
                ('cancellationReason', models.CharField(blank=True, max_length=255)),
                ('promoter', models.CharField(max_length=255)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TicketCreatedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.buyer')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doors', models.TimeField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.ticket')),
            ],
        ),
    ]
