# Generated by Django 4.2.7 on 2023-12-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='doors',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_amount',
            field=models.CharField(max_length=255),
        ),
    ]
